# Generated by Django 2.2.5 on 2022-07-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='chek_in',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='chek_out',
            new_name='check_out',
        ),
    ]
