# Generated by Django 2.2.5 on 2022-07-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220713_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='chek_in',
            new_name='check_in',
        ),
    ]
